import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link"
/*

Landing/Main page
*/

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>10 Min Maths</title>
        {/* TODO ! Add all the required headers here */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className={styles.main}>
        <div>
          <h1>10 Min Maths</h1>
          <p>
            Daily problems to solve in 10 mins!
          </p>
        </div>
        <div>
          <Link>
            Start the challenge!
          </Link>
          <p>
            Once you press start, a timer will start. <span>Leaving the page will forfeit your response</span>
          </p>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
