import Head from "next/head"

export default function SignUp() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>
            Signup!!
          </title>
          {/* TODO ! Add all the required headers here */}
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Stuff goes here */}
      </div>
    </>
  );
}
